drop table if exists PARKINGSLOT;
drop table if exists PARKING_INFO;

CREATE TABLE PARKINGSLOT ("ID" LONG NOT NULL AUTO_INCREMENT, "PARKING_NO" VARCHAR(20), "STATUS" VARCHAR(20));
	   
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (1,'101','VACANT');
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (2,'102','VACANT');
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (3,'103','VACANT');
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (4,'104','VACANT');
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (5,'105','VACANT');
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (6,'106','VACANT');
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (7,'107','VACANT');
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (8,'108','VACANT');
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (9,'109','VACANT');
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (10,'110','VACANT');
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (11,'111','VACANT');
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (12,'112','VACANT');
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (13,'113','VACANT');
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (14,'114','VACANT');
insert into PARKINGSLOT(ID,PARKING_NO,STATUS) values (15,'115','VACANT');

CREATE TABLE PARKING_INFO  ("ID" LONG NOT NULL AUTO_INCREMENT, "PARKING_NO" VARCHAR(20), "VEHICLE_NO" VARCHAR(20), "ENTRY_DATE" DATE, "EXIT_DATE" DATE, "TICKET_NO" VARCHAR(20));